
CREATE PROCEDURE dbo.Sets
AS
SET ANSI_NULLS  OFF
SET ANSI_PADDING OFF
SET ANSI_WARNINGS OFF
SET ARITHABORT OFF
SET NUMERIC_ROUNDABORT ON
SET QUOTED_IDENTIFIER OFF
SET CONCAT_NULL_YIELDS_NULL OFF

-- SML013, SML014, SML015, SML016, SML017, SML018, SML019, SML030 
